In [1]:
import pandas as pd
import torch

In [2]:
import pandas as pd
import torch

# Given DataFrame
data = {'player': ['Player1', 'Player2', 'Player3', 'Player1', 'Player2', 'Player3'],
        'round_id': [1, 1, 1, 2, 2, 2],
        'stat1': [10, 15, 20, 25, 30, 35],
        'stat2': [50, 55, 60, 65, 70, 75]}

df = pd.DataFrame(data)

# Pivot the DataFrame to reshape it
df_pivot = df.pivot(index='round_id', columns='player')

# Convert the DataFrame to a NumPy array
array = df_pivot.to_numpy()

# Convert the NumPy array to a PyTorch tensor
tensor = torch.tensor(array)

# Print the resulting tensor
print(tensor)


tensor([[10, 15, 20, 50, 55, 60],
        [25, 30, 35, 65, 70, 75]])


In [3]:
tensor.size()

torch.Size([2, 6])

In [4]:
import pandas as pd
import torch

# Given DataFrame
data = {'player': ['Player1', 'Player2', 'Player3', 'Player1', 'Player2', 'Player3'],
        'round_id': [1, 1, 1, 2, 2, 2],
        'stat1': [10, 15, 20, 25, 30, 35],
        'stat2': [50, 55, 60, 65, 70, 75]}

df = pd.DataFrame(data)

# Pivot the DataFrame to reshape it
df_pivot = df.set_index(['round_id', 'player']).unstack()

# Convert the DataFrame to a NumPy array
array = df_pivot.to_numpy()

# Convert the NumPy array to a PyTorch tensor
tensor = torch.tensor(array)

# Print the resulting tensor
print(tensor)


tensor([[10, 15, 20, 50, 55, 60],
        [25, 30, 35, 65, 70, 75]])


In [5]:
df_pivot

stat1                   stat2                
player   Player1 Player2 Player3 Player1 Player2 Player3
round_id                                                
1             10      15      20      50      55      60
2             25      30      35      65      70      75

In [11]:
import pandas as pd
  
# initialize data of lists.
data = {'Animal':['Cat', 'Dog', 'Dog', 'Dog'],
        'Country':["USA", "Canada", "USA", "Canada"],
        'Likes': ['Petting', 'Hunting', 'Petting', 'Petting'], 
         'Age':[1, 2, 3, 4]}

# there are no duplicate lines in terms of Animal, Country and Likes, so I do not need any aggregation function
  
# Create DataFrame
dfAnimals = pd.DataFrame(data)
dfAnimals

Animal Country    Likes  Age
0    Cat     USA  Petting    1
1    Dog  Canada  Hunting    2
2    Dog     USA  Petting    3
3    Dog  Canada  Petting    4

In [20]:
import pandas as pd
import numpy as np
import torch

df = pd.DataFrame(data)

CAT = df.columns.tolist()
CAT.remove("Age")

# encode categories as integers and extract the shape
shape = []
for c in CAT:
    shape.append(len(df[c].unique()))
    df[c] = df[c].astype("category").cat.codes
shape = tuple(shape)

print(df)

# get indices as tuples and corresponding values
idx = [tuple(t) for t in df.values[:,:-1]]
values = df.values[:,-1]

print("idx")
print(idx)

print("values")
print(values)
# init final matrix with zeros and fill it from indices
A = np.zeros(shape)
for i, v in zip(idx,values):
    A[i] = v
    print(i, v)

# convert to pytorch tensor
A = torch.tensor(A)
print(A)

   Animal  Country  Likes  Age
0       0        1      1    1
1       1        0      0    2
2       1        1      1    3
3       1        0      1    4
idx
[(0, 1, 1), (1, 0, 0), (1, 1, 1), (1, 0, 1)]
values
[1 2 3 4]
(0, 1, 1) 1
(1, 0, 0) 2
(1, 1, 1) 3
(1, 0, 1) 4
tensor([[[0., 0.],
         [0., 1.]],

        [[2., 4.],
         [0., 3.]]], dtype=torch.float64)
